### ISSUE TITLE
PostProcess module missing

### ISSUE THREAD

**Issue by JosephBChoi** [USTB-AI3DVIP/matsam#1]
`PostProcess` module is missing to run the `matsam_example.ipynb` notebook.

**Comment by USTB-AI3DVIP** [comment]
The PostProcess module is imported in `matsam_example.ipynb` first code block, specifically: `from utils.metrics import *`.  
Please check if there is a `metrics.py` file in the utils folder.

**Comment by JosephBChoi** [comment]
Thank for the instruction. It worked.
